- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 0.5h
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: ValetGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ValetPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ServiceWorkerChameleonOutfit
  job: ServiceWorker
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
