# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 4h # harmony: 5h -> 4h
  weight: 10
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4h # harmony: 10h -> 4h
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  # CD: Skip records
  special:
    - !type:AddComponentSpecial
      components:
        - type: SkipLoadingCharacterRecords
  # end CD
  applyTraits: false
