# SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2024 TsjipTsjip <19798667+TsjipTsjip@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # Harmony start
    - name: Automatic Maintenance Label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.pull_request.title, 'Upstream') || startsWith(github.event.pull_request.title, 'Changelog') }}
      with:
        labels: Maintenance
    - uses: snnaplab/get-labels-action@v1.0.1
      continue-on-error: true
    # Harmony end
    - uses: actions/labeler@v5
      # Harmony start
      if: ${{ (env.LABELS == '') || (! contains(env.LABELS, 'Maintenance')) }}
      with:
        sync-labels: true
      # Harmony end
